# YAML: DioDocs用Container Appsをデプロイするジョブを追加

name: Build and deploy Python app to Azure Web App - OpenAIhiramatsu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      # pip依存パッケージのキャッシュを追加
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # アーティファクトのZIP作成
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  diodocs-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/diodocs-container:latest ./diodocs-container
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/diodocs-container:latest

  diodocs-deploy:
    runs-on: ubuntu-latest
    needs: diodocs-build

    steps:
      - name: Deploy to Azure Container Apps
        uses: azure/cli@v1
        with:
          inlineScript: |
            az containerapp update \
              --name diodocs-api \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --image ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/diodocs-container:latest \
              --cpu 0.5 \
              --memory 1.0Gi
